Repository ricardocuellar/proyectoIntegradorBackend-team1, pull requests merged in 2025-03, with the labels that each got.

#6 endpoints servicios y categorias
  src/main/java/com/petcare/backend/proyectoIntegrador/DTO/CategoriaResponse.java
  src/main/java/com/petcare/backend/proyectoIntegrador/DTO/ServicioRequest.java
  src/main/java/com/petcare/backend/proyectoIntegrador/DTO/ServicioResponse.java
  src/main/java/com/petcare/backend/proyectoIntegrador/DTO/ServicioSinCategoriaResponse.java
  src/main/java/com/petcare/backend/proyectoIntegrador/config/SecurityConfig.java
  src/main/java/com/petcare/backend/proyectoIntegrador/controller/CategoriaController.java
  src/main/java/com/petcare/backend/proyectoIntegrador/controller/ServicioController.java
  src/main/java/com/petcare/backend/proyectoIntegrador/entity/Categoria.java
  src/main/java/com/petcare/backend/proyectoIntegrador/entity/Servicio.java
  src/main/java/com/petcare/backend/proyectoIntegrador/repository/ICategoriaRepository.java
  src/main/java/com/petcare/backend/proyectoIntegrador/service/ICategoriaService.java
  src/main/java/com/petcare/backend/proyectoIntegrador/service/IServicioService.java
  src/main/java/com/petcare/backend/proyectoIntegrador/service/impl/CategoriaServiceImpl.java
  src/main/java/com/petcare/backend/proyectoIntegrador/service/impl/ServicioServiceImpl.java
  src/main/java/com/petcare/backend/proyectoIntegrador/util/DtoConverter.java
Labels: enhancement

#7 cateoria entity
  src/main/java/com/petcare/backend/proyectoIntegrador/controller/CategoriaController.java
  src/main/java/com/petcare/backend/proyectoIntegrador/entity/Categoria.java
Labels: enhancement

#8 cors conflict
  src/main/java/com/petcare/backend/proyectoIntegrador/config/SecurityConfig.java
Labels: enhancement

#9 actualizar categoria
  src/main/java/com/petcare/backend/proyectoIntegrador/controller/CategoriaController.java
  src/main/java/com/petcare/backend/proyectoIntegrador/controller/FavoritosController.java
  src/main/java/com/petcare/backend/proyectoIntegrador/entity/Categoria.java
Labels: enhancement

#11 Change Services GET endpoints to public access.
  src/main/java/com/petcare/backend/proyectoIntegrador/config/SecurityConfig.java
Labels: bug, enhancement

#12 Add cors configuration source to securityFilter
  src/main/java/com/petcare/backend/proyectoIntegrador/config/SecurityConfig.java
Labels: enhancement

#13 envio de correo y rating
  pom.xml
  src/main/java/com/petcare/backend/proyectoIntegrador/DTO/EnviarConfirmacionRequest.java
  src/main/java/com/petcare/backend/proyectoIntegrador/DTO/ServicioResponse.java
  src/main/java/com/petcare/backend/proyectoIntegrador/DTO/ServicioSinCategoriaResponse.java
  src/main/java/com/petcare/backend/proyectoIntegrador/controller/AuthController.java
  src/main/java/com/petcare/backend/proyectoIntegrador/controller/ServicioController.java
  src/main/java/com/petcare/backend/proyectoIntegrador/entity/Servicio.java
  src/main/java/com/petcare/backend/proyectoIntegrador/service/IAuthService.java
  src/main/java/com/petcare/backend/proyectoIntegrador/service/IServicioService.java
  src/main/java/com/petcare/backend/proyectoIntegrador/service/impl/AuthServiceImpl.java
  src/main/java/com/petcare/backend/proyectoIntegrador/service/impl/ServicioServiceImpl.java
  src/main/java/com/petcare/backend/proyectoIntegrador/util/DtoConverter.java
  src/main/java/com/petcare/backend/proyectoIntegrador/util/TemplateLoader.java
  src/main/resources/application.properties
  src/main/resources/templates/confirmacion.html
Labels: enhancement

#14 Hot Fix, solve backend types errors
  src/main/java/com/petcare/backend/proyectoIntegrador/DTO/ServicioResponse.java
  src/main/java/com/petcare/backend/proyectoIntegrador/DTO/ServicioSinCategoriaResponse.java
  src/main/java/com/petcare/backend/proyectoIntegrador/entity/Servicio.java
Labels: bug

#15 Hotfix solve types errors
  src/main/java/com/petcare/backend/proyectoIntegrador/DTO/ServicioSinCategoriaResponse.java
Labels: bug

#16 feat: compile fixes
  .gitignore
  pom.xml
  src/main/java/com/petcare/backend/proyectoIntegrador/ProyectoIntegradorApplication.java
  src/main/resources/application.properties
  src/test/java/com/petcare/backend/proyectoIntegrador/ServicioRequestTest.java
Labels: enhancement

#17 PR for Backend deploy
  .github/workflows/build.yml
  .gitignore
  Dockerfile
  pom.xml
  src/main/java/com/petcare/backend/proyectoIntegrador/ProyectoIntegradorApplication.java
  src/main/java/com/petcare/backend/proyectoIntegrador/config/SecurityConfig.java
  src/main/resources/application.properties
  uploads/1740674674109_Screenshot 2024-09-09 155635.png
Labels: enhancement
